In [1]:
myPoint_1=[0,0]
myPoint_2=[1,0]
myPoint_3=[0,1]
myPoint_4=[1,1]

In [2]:
#Dört tane noktanın orta noktası.
a=myPoint_1[0]+myPoint_2[0]+myPoint_3[0]+myPoint_4[0]
b=myPoint_1[1]+myPoint_2[1]+myPoint_3[1]+myPoint_4[1]
center_Point=(a/4,b/4)
center_Point

(0.5, 0.5)

In [2]:
#Yukarıdaki yapının fonksiyon halinde yapılmış hali
def findCenter(List_of_Points):
    x=0
    y=0
    for point in List_of_Points:
        x=x+point[0]
        y=y+point[1]
    length=len(List_of_Points)
    return [x/length,y/length]

In [3]:
myPoint_1=[0,0]
myPoint_2=[1,0]
myPoint_3=[0,1]
myPoint_4=[1,1]

In [4]:
my_Point_List=[]
my_Point_List.append(myPoint_1)
my_Point_List.append(myPoint_2)
my_Point_List.append(myPoint_3)
my_Point_List.append(myPoint_4)

In [5]:
len(my_Point_List)

4

In [6]:
center=findCenter(my_Point_List)
center

[0.5, 0.5]

In [11]:
import numpy as np
my_Array=np.array([[1,2,3],[2,6,9]],np.int32)
print(my_Array)

[[1 2 3]
 [2 6 9]]


In [9]:
my_Array.ndim, my_Array.shape

(2, (2, 3))

In [12]:
my_Array_1=my_Array.reshape(1,6)
print(my_Array_1)

[[1 2 3 2 6 9]]
