In [1]:
myList = [ 1,3,4,2,1,5,7,9,5,2,1,40 ]

In [2]:
myList

[1, 3, 4, 2, 1, 5, 7, 9, 5, 2, 1, 40]

In [3]:
import numpy as np

In [4]:
np.random.randint(2,5,5)

array([2, 2, 2, 2, 4])

In [5]:
my_Numbers=np.random.randint(1,10,5)

In [6]:
my_Numbers

array([8, 6, 8, 7, 4])

In [9]:
myHistogram=[[my_Numbers[0],1]]
my_Numbers , myHistogram , len(myHistogram)

(array([8, 6, 8, 7, 4]), [[8, 1]], 1)

In [15]:
#Burada bir tupple oluşturuyoruz.Histogram(bir dizideki sayıdan o dizide kaç tane olduğunu gösterir.)
for number in my_Numbers:
    for index , counter in enumerate (myHistogram):
        if(len(myHistogram))!= 0:
            for histItem in myHistogram:
                if (number==histItem[0]):
                    histItem[1]=histItem[1]+1
                else:
                    myHistogram.append([number,1])
            else:
            myHistogram.append([number,1])
myHistogram

#yapmak istediğimiz yapı tupple de yok ve bunu list de dene.

IndentationError: expected an indented block (<ipython-input-15-a0b7c3a1f640>, line 11)

In [16]:
var_1=(1,2,3)
var_2=(2,5,3)
var_3=(1,5,3)
var_4=(2,5,6)

In [17]:
if var_1[2]==var_2[2]:
    print("1 ve 2 nin 3. degerleri esit")
else:
    print("4 ve 2 esit DEGIL")

1 ve 2 nin 3. degerleri esit
